_prefs: 
  mapid: ''
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -96.416
  - -0.0439
  - 4
description: Mars Terrain
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - mapbox_mars_satellite
  - contour.line
  - hillshade
  - place
  - contour.label
maxzoom: 10
minzoom: 0
name: Mars Terrain
source: "mapbox:///mapbox.mars-satellite,mapbox.mars-terrain-v1"
styles: 
  - style.mss
template: ''
